default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: <%= ENV['DATABASE_USERNAME'] %>
  host: localhost

development:
  <<: *default
  database: test_auth_development

test:
  <<: *default
  database: test_auth_test

production:
  <<: *default
  database: test_auth_production
  username: <%= ENV['DATABASE_USERNAME'] %>
  password: <%= ENV['DATABASE_PASSWORD'] %>
